LPAL-588 add content-security-policy and x-content-security-policy headers
ministryofjustice/opg-lpa pull request #1323
Opened 2023-01-30 18:03 UTC by nickdavis2001

## Purpose

_LPAL-588 add content-security-policy and x-content-security-policy headers_

## Approach

_Add headers to PHP, and to nginx in case PHP ever loses its headers. Also check in cypress test.  2 weird things to note- (1) had to do formatting that looks inconsistent to me on the js to keep prettier happy. (2) a semi-colon at the end is expected for content-security-policy but not for x-content-security-policy_

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added mandatory tags to terraformed resources, where possible
* [ ] If I have a new OPG component dependency, I have updated the `metadata.json` with the repo location.
* [ ] If I added a package.json or composer.json, I also made sure this is included in the script in `.github/workflows/dependabot-update.yml`
* [ ] The product team have tested these changes

2023-01-31 10:08 UTC, townxelliot approved these changes

2023-01-31 10:08 UTC, townxelliot commented on service-front/module/Application/src/Controller/AbstractBaseController.php
> +        $response->getHeaders()->addHeaders([
Could these lines be merged into the previous addHeaders() call?

2023-01-31 10:08 UTC, townxelliot commented on service-front/module/Application/src/Controller/AbstractBaseController.php
> +            'X-Content-Security-Policy' => $securityPolicy
ditto

2023-02-28 11:51 UTC, nickdavis2001 commented on service-front/module/Application/src/Controller/AbstractBaseController.php
> +            'X-Content-Security-Policy' => $securityPolicy
Done, was temporary measure while debugging.

2023-03-01 08:59 UTC, townxelliot requested changes

2023-03-01 16:08 UTC, nickdavis2001 commented on service-front/assets/js/main.js
> +var dashboard = function () {
No longer needed now, so removed

2023-03-01 17:00 UTC, townxelliot approved these changes

2023-03-08 10:00 UTC, townxelliot approved these changes

2023-03-08 13:48 UTC, merged