LPAL-478 Add precommit hooks with instructions
ministryofjustice/opg-lpa pull request #598
Opened 2021-08-19 14:53 UTC by williamfalconeruk

## Purpose

This PR enables pre-commithooks and adds to existing ones to cover php and secrets.
this is to ensure developers/ webops are checking in standardised code.
This is a first attempt and will need tweaking as needed.

Fixes LPAL-478

## Approach

Add Precommit hooks for:
- PHP
- Secrets scanning

make precommit functional and update readme with install instructions.

## Learning

- https://pre-commit.com/index.html
- https://pre-commit.com/hooks.html
- https://github.com/digitalpulp/pre-commit-php
- https://github.com/zricethezav/gitleaks

## Checklist

* [x] I have performed a self-review of my own code
* [x] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added mandatory tags to terraformed resources, where possible
* [ ] If I added a package.json or composer.json, I also made sure this is included in the script in `.github/workflows/dependabot-update.yml`
* [ ] The product team have tested these changes

2021-08-19 15:07 UTC, townxelliot requested changes
Looks good, just a few typos

2021-08-19 15:08 UTC, williamfalconeruk commented on README.md
> +please install the precommit hooks as follows in the root of the repo directory (Mac only):
```suggestion
Install the precommit hooks as follows in the root of the repo directory (Mac only):
```

2021-08-19 15:09 UTC, williamfalconeruk commented on README.md
> +This will install the precommit hooks for the repo. this covers:
```suggestion
This will install the pre-commit hooks for the repo. This covers:
```

2021-08-19 15:09 UTC, williamfalconeruk commented on README.md
> +For linux users, revert to the instructions for installing phpcs, phpstan and precommit hooks:
```suggestion
For Linux users, revert to the instructions for installing phpcs, phpstan and pre-commit hooks:
```

2021-08-19 15:10 UTC, williamfalconeruk commented on README.md
> +### install pre-commit hooks (mac)
```suggestion
### install pre-commit hooks (mac)
```

2021-08-19 15:11 UTC, williamfalconeruk commented on README.md
> +### clone repo
```suggestion
### Clone repo
```

2021-08-19 15:11 UTC, williamfalconeruk commented on README.md
> +### install pre-commit hooks (mac)
```suggestion
### Install pre-commit hooks (mac)
```

2021-08-20 08:36 UTC, townxelliot approved these changes

2021-08-20 08:50 UTC, merged