LPAL-722 Roll-up dependabot updates and fix issues
ministryofjustice/opg-lpa pull request #875
Opened 2022-04-07 12:56 UTC by townxelliot

## Purpose

[LPAL-722](https://opgtransform.atlassian.net/browse/LPAL-722)

Fixes LPAL-722

## Approach

Incorporates dependabot PRs:

* https://github.com/ministryofjustice/opg-lpa/pull/870
* https://github.com/ministryofjustice/opg-lpa/pull/869
* https://github.com/ministryofjustice/opg-lpa/pull/868
* https://github.com/ministryofjustice/opg-lpa/pull/859

Suggest we close this one - https://github.com/ministryofjustice/opg-lpa/pull/840 - as PHP 8.1 is not compatible with Laminas.

I've run unit tests and cypress tests locally and they are passing OK.

## Learning

n/a

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added mandatory tags to terraformed resources, where possible
* [ ] If I added a package.json or composer.json, I also made sure this is included in the script in `.github/workflows/dependabot-update.yml`
* [ ] The product team have tested these changes

2022-04-08 08:35 UTC, Raffers commented on service-front/module/Application/tests/Model/Service/Session/FilteringSaveHandlerTest.php
>  }
You no longer have the pre-commit hooks installed?

2022-04-08 09:05 UTC, Raffers approved these changes

2022-04-12 08:07 UTC, williamfalconeruk requested changes
As per comment re critical bug.

2022-04-12 08:13 UTC, williamfalconeruk commented
LPAL-731 raised to address this vuln first.

2022-04-13 10:43 UTC, williamfalconeruk approved these changes

2022-04-13 10:44 UTC, williamfalconeruk commented
This has been fixed in front, so we can proceed.

2022-04-13 10:45 UTC, williamfalconeruk approved these changes

2022-04-19 07:56 UTC, williamfalconeruk approved these changes

2022-04-19 07:56 UTC, merged