[LPAL-705] Add prompts for signing continuation sheets in the date checker
ministryofjustice/opg-lpa pull request #983
Opened 2022-06-13 13:57 UTC by mabely

## Purpose

Additional instructions on when to sign continuation sheets need to be added to the date checker tool to help users with the order or timing of signing certain documents. 

Continuation sheets are generated when the users inputs more than default number of fields provided (eg. number of attorneys). 

[LPAL-705](https://opgtransform.atlassian.net/browse/LPAL-705)

## Approach

Existing logic is extracted into a service to reuse for working out when certain continuation sheets would be generated. This is passed to the front end to conditionally render the relevant messages. 

The service was untested so unit tests have been back filled to cover the key branches of logic. I have added an LPA to the database seed for Cypress tests in order to test a scenario where multiple of these messages would be relevant. The only way to implement Cypress tests for it was to pre-seed the database. 

NB the date check tool isn't covered by any Cypress tests, I have added a comment in the code and a ticket to back fill this.

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added mandatory tags to terraformed resources, where possible
* [ ] If I added a package.json or composer.json, I also made sure this is included in the script in `.github/workflows/dependabot-update.yml`
* [ ] The product team have tested these changes

2022-06-13 14:22 UTC, townxelliot requested changes
Good job. I think it's well worth refactoring this so we can unit test it. Most of my comments are to do with tabs creeping in instead of spaces. There are also a few conflicts to fix: the files you've edited inside the cypress folder have moved from cypress/integration to cypress/e2e (as part of the upgrade to cypress 10).

2022-06-13 14:43 UTC, townxelliot commented
Apologies @mabely only just noticed this is a draft. I should have waited until you specified the PR was ready for a review.

2022-06-13 16:19 UTC, mabely commented on service-front/module/Application/view/application/authenticated/dashboard/macros.twig
> +						<li class="list-item list-item--v3 status-container--{{ status }}" {% if lpa.refreshId %}data-refresh-id="{{ lpa.refreshId }}"{% endif %} data-cy=lpa-{{ lpa.id }}>
Removed 👍🏼 Not sure how that got in there

2022-06-13 16:19 UTC, mabely commented on service-front/module/Application/view/application/authenticated/lpa/date-check/index.twig
> +			{% if continuationNoteKeys is not empty %}
Fixed

2022-06-14 14:07 UTC, townxelliot submitted a review, later dismissed

2022-06-15 06:23 UTC, townxelliot commented on service-front/module/Application/src/Controller/Authenticated/Lpa/DateCheckController.php
> +                // phpcs:disable
Rather than ignore errors from the linter, fix them if possible. Our setup insists that lines have to be <= 120 chars.

2022-06-15 06:37 UTC, townxelliot commented
I think your composer.lock files may be merged incorrectly, as a guzzlehttp/guzzle vulnerability is present again, which was fixed by a previous commit. We'll need to do some comparisons between your composer.json files and those in main to ensure we aren't rolling back to previous library versions by accident.

2022-06-15 06:41 UTC, townxelliot commented
Just checked this over, and looks like composer.lock in the root directory has the vulnerability. I'm not sure why we have this anyway: I don't think it's used by anything and could probably be removed. Could you have a look to see whether we're using it for anything please @mabely and get rid of it if not?

2022-06-15 10:53 UTC, mabely commented
> Good job. I think it's well worth refactoring this so we can unit test it. Most of my comments are to do with tabs creeping in instead of spaces. There are also a few conflicts to fix: the files you've edited inside the cypress folder have moved from cypress/integration to cypress/e2e (as part of the upgrade to cypress 10).

@townxelliot which part is worth refactoring - the method `getContinuationNoteKeys`?

2022-07-14 08:55 UTC, nickdavis2001 commented on cypress/e2e/common/i_click.js
> +When(`I click {string} for LPA ID {int}`, (clickable, LpaId) => {
Nice :)

2022-07-14 09:01 UTC, nickdavis2001 approved these changes
🏆 very nice especially cypress tests. :)

2022-07-14 10:08 UTC, merged